-- =====================================================
-- LOADS MODULE - SUPABASE SCHEMA (Compatible)
-- =====================================================

-- 1. TMS Customers Table
CREATE TABLE IF NOT EXISTS public.tms_customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TMS Carriers Table
CREATE TABLE IF NOT EXISTS public.tms_carriers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    mc_number TEXT UNIQUE,
    dot_number TEXT,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive', 'Pending')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TMS Agents Table
CREATE TABLE IF NOT EXISTS public.tms_agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    commission_rate DECIMAL(5,2) DEFAULT 10.00,
    status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Loads Table
CREATE TABLE IF NOT EXISTS public.loads (
    id TEXT PRIMARY KEY,
    customer_id BIGINT REFERENCES public.tms_customers(id) ON DELETE SET NULL,
    customer_name TEXT,
    carrier_id BIGINT REFERENCES public.tms_carriers(id) ON DELETE SET NULL,
    carrier_name TEXT,
    agent_id BIGINT REFERENCES public.tms_agents(id) ON DELETE SET NULL,
    agent_name TEXT,
    pickup_address TEXT NOT NULL,
    delivery_address TEXT NOT NULL,
    rate DECIMAL(10,2) NOT NULL,
    carrier_cost DECIMAL(10,2) NOT NULL DEFAULT 0,
    trip_distance INTEGER,
    equipment_type TEXT CHECK (equipment_type IN ('Dry Van', 'Reefer', 'Flatbed', 'Power Only')),
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Booked', 'Delivered', 'Cancelled')),
    reference_number TEXT,
    notes TEXT,
    appointment_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_loads_customer_id ON public.loads(customer_id);
CREATE INDEX IF NOT EXISTS idx_loads_carrier_id ON public.loads(carrier_id);
CREATE INDEX IF NOT EXISTS idx_loads_agent_id ON public.loads(agent_id);
CREATE INDEX IF NOT EXISTS idx_loads_status ON public.loads(status);
CREATE INDEX IF NOT EXISTS idx_loads_created_at ON public.loads(created_at DESC);

-- Enable RLS
ALTER TABLE public.tms_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tms_carriers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tms_agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loads ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DROP POLICY IF EXISTS "Admin Full Access - Customers" ON public.tms_customers;
CREATE POLICY "Admin Full Access - Customers"
ON public.tms_customers FOR ALL
TO authenticated
USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Carriers" ON public.tms_carriers;
CREATE POLICY "Admin Full Access - Carriers"
ON public.tms_carriers FOR ALL
TO authenticated
USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Agents" ON public.tms_agents;
CREATE POLICY "Admin Full Access - Agents"
ON public.tms_agents FOR ALL
TO authenticated
USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Loads" ON public.loads;
CREATE POLICY "Admin Full Access - Loads"
ON public.loads FOR ALL
TO authenticated
USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

-- Helper function for load ID generation
CREATE OR REPLACE FUNCTION public.generate_load_id()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    year INTEGER;
    max_num INTEGER;
    next_num TEXT;
BEGIN
    year := EXTRACT(YEAR FROM NOW());
    
    SELECT COALESCE(MAX(CAST(SPLIT_PART(id, '-', 3) AS INTEGER)), 0)
    INTO max_num
    FROM public.loads
    WHERE id LIKE 'L-' || year || '-%';
    
    next_num := LPAD((max_num + 1)::TEXT, 4, '0');
    
    RETURN 'L-' || year || '-' || next_num;
END;
$$;

-- Sample data
INSERT INTO public.tms_agents (id, name, email, commission_rate) VALUES
(1, 'Ozan Akdemir', 'ozan@loyalbrokerage.com', 10.00),
(2, 'Jane Smith', 'jane@loyalbrokerage.com', 10.00),
(3, 'David Lopez', 'david@loyalbrokerage.com', 10.00)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tms_customers (id, name, contact_name, email, phone, address) VALUES
(1, 'ABC Manufacturing', 'John Smith', 'john@abcmfg.com', '555-0101', '1234 Industrial Pkwy, Chicago, IL'),
(2, 'Max Steel Inc', 'Sarah Johnson', 'sarah@maxsteel.com', '555-0102', '789 Steel Ave, Pittsburgh, PA'),
(3, 'Global Trade Solutions', 'Mike Chen', 'mike@globaltrade.com', '555-0103', '456 Port St, Los Angeles, CA')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tms_carriers (id, name, mc_number, dot_number, contact_name, email, phone, status) VALUES
(1, 'Ada Fleet LLC', 'MC123456', 'DOT789012', 'Tom Wilson', 'dispatch@adafleet.com', '555-0201', 'Active'),
(2, 'Swift Carriers', 'MC234567', 'DOT890123', 'Linda Garcia', 'ops@swiftcarriers.com', '555-0202', 'Active'),
(3, 'Reliable Transport', 'MC345678', 'DOT901234', 'Bob Anderson', 'dispatch@reliabletrans.com', '555-0203', 'Active')
ON CONFLICT (id) DO NOTHING;
