-- =====================================================
-- TMS COMPLETE SYSTEM SCHEMA - SUPABASE COMPATIBLE
-- =====================================================
-- All 9 modules consolidated
-- Ready for Supabase Studio SQL Editor
-- =====================================================

-- =====================================================
-- MODULE 1: CORE ENTITIES (Customers, Carriers, Agents)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tms_customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    payment_terms TEXT DEFAULT 'Net 30',
    credit_status TEXT DEFAULT 'Approved' CHECK (credit_status IN ('Approved', 'Review', 'Denied')),
    avg_rate DECIMAL(10,2),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tms_carriers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    mc_number TEXT UNIQUE,
    dot_number TEXT,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    insurance_expiry DATE,
    credit_status TEXT DEFAULT 'Approved' CHECK (credit_status IN ('Approved', 'Review', 'Denied')),
    status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive', 'Pending')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tms_agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    commission_rate DECIMAL(5,2) DEFAULT 10.00,
    hire_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- MODULE 2: LOADS MANAGEMENT
-- =====================================================

CREATE TABLE IF NOT EXISTS public.loads (
    id TEXT PRIMARY KEY,
    customer_id BIGINT REFERENCES public.tms_customers(id) ON DELETE SET NULL,
    customer_name TEXT,
    carrier_id BIGINT REFERENCES public.tms_carriers(id) ON DELETE SET NULL,
    carrier_name TEXT,
    agent_id BIGINT REFERENCES public.tms_agents(id) ON DELETE SET NULL,
    agent_name TEXT,
    pickup_address TEXT NOT NULL,
    delivery_address TEXT NOT NULL,
    rate DECIMAL(10,2) NOT NULL,
    carrier_cost DECIMAL(10,2) NOT NULL DEFAULT 0,
    trip_distance INTEGER,
    equipment_type TEXT CHECK (equipment_type IN ('Dry Van', 'Reefer', 'Flatbed', 'Power Only')),
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Booked', 'Delivered', 'Cancelled')),
    reference_number TEXT,
    notes TEXT,
    appointment_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- MODULE 3: CRM (Opportunities & Pipeline)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.crm_opportunities (
    id TEXT PRIMARY KEY,
    customer_name TEXT NOT NULL,
    contact_email TEXT,
    contact_phone TEXT,
    company_name TEXT,
    carrier_name TEXT,
    load_id TEXT REFERENCES public.loads(id) ON DELETE SET NULL,
    stage TEXT DEFAULT 'Prospect' CHECK (stage IN ('Prospect', 'Lead', 'Qualified', 'Customer', 'Repeat')),
    estimated_rate DECIMAL(10,2),
    agent_id BIGINT REFERENCES public.tms_agents(id) ON DELETE SET NULL,
    agent_name TEXT,
    notes TEXT,
    next_follow_up DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.crm_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id TEXT REFERENCES public.crm_opportunities(id) ON DELETE CASCADE,
    activity_type TEXT CHECK (activity_type IN ('Call', 'Email', 'Meeting', 'Note')),
    description TEXT NOT NULL,
    agent_id BIGINT REFERENCES public.tms_agents(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- MODULE 4: ACCOUNTING (Invoices, Payments, Commissions)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.invoices (
    id TEXT PRIMARY KEY,
    load_id TEXT REFERENCES public.loads(id) ON DELETE SET NULL,
    customer_id BIGINT REFERENCES public.tms_customers(id) ON DELETE SET NULL,
    customer_name TEXT,
    amount DECIMAL(10,2) NOT NULL,
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Paid', 'Overdue', 'Cancelled')),
    date_sent DATE DEFAULT CURRENT_DATE,
    date_paid DATE,
    due_date DATE,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id TEXT REFERENCES public.invoices(id) ON DELETE SET NULL,
    amount DECIMAL(10,2) NOT NULL,
    payment_date DATE DEFAULT CURRENT_DATE,
    payment_method TEXT CHECK (payment_method IN ('ACH', 'Wire', 'Check', 'Credit Card')),
    reference_number TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.agent_commissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id TEXT REFERENCES public.loads(id) ON DELETE CASCADE,
    agent_id BIGINT REFERENCES public.tms_agents(id) ON DELETE CASCADE,
    agent_name TEXT,
    gross_profit DECIMAL(10,2) NOT NULL,
    commission_rate DECIMAL(5,2) NOT NULL,
    commission_amount DECIMAL(10,2) NOT NULL,
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Paid')),
    paid_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.receivables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id TEXT REFERENCES public.invoices(id) ON DELETE CASCADE,
    customer_id BIGINT REFERENCES public.tms_customers(id) ON DELETE SET NULL,
    customer_name TEXT,
    due_amount DECIMAL(10,2) NOT NULL,
    days_outstanding INTEGER,
    status TEXT CHECK (status IN ('Current', 'Overdue')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL CHECK (category IN ('Fuel', 'Maintenance', 'Dispatch', 'Insurance', 'Other')),
    description TEXT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    truck TEXT,
    expense_date DATE DEFAULT CURRENT_DATE,
    receipt_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- MODULE 5: AGENT PERFORMANCE & GOALS
-- =====================================================

CREATE TABLE IF NOT EXISTS public.agent_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT REFERENCES public.tms_agents(id) ON DELETE CASCADE,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    loads_closed INTEGER DEFAULT 0,
    revenue DECIMAL(10,2) DEFAULT 0,
    profit DECIMAL(10,2) DEFAULT 0,
    commission DECIMAL(10,2) DEFAULT 0,
    conversion_rate DECIMAL(5,2),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(agent_id, period_start, period_end)
);

CREATE TABLE IF NOT EXISTS public.agent_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT REFERENCES public.tms_agents(id) ON DELETE CASCADE,
    goal_type TEXT CHECK (goal_type IN ('Revenue', 'Loads', 'Profit', 'Commission')),
    target_value DECIMAL(10,2) NOT NULL,
    period TEXT CHECK (period IN ('Weekly', 'Monthly', 'Quarterly', 'Yearly')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- MODULE 6: SYSTEM USERS & ROLES
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tms_users (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    role TEXT DEFAULT 'agent' CHECK (role IN ('admin', 'agent', 'dispatcher', 'accountant')),
    agent_id BIGINT REFERENCES public.tms_agents(id) ON DELETE SET NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- MODULE 7: SETTINGS & PREFERENCES
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tms_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    setting_key TEXT NOT NULL,
    setting_value JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, setting_key)
);

-- =====================================================
-- MODULE 8: ACTIVITY LOGS & AUDIT TRAIL
-- =====================================================

CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('create', 'update', 'delete', 'view')),
    changes JSONB,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- INDEXES
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_loads_customer_id ON public.loads(customer_id);
CREATE INDEX IF NOT EXISTS idx_loads_carrier_id ON public.loads(carrier_id);
CREATE INDEX IF NOT EXISTS idx_loads_agent_id ON public.loads(agent_id);
CREATE INDEX IF NOT EXISTS idx_loads_status ON public.loads(status);
CREATE INDEX IF NOT EXISTS idx_loads_created_at ON public.loads(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_crm_opportunities_agent_id ON public.crm_opportunities(agent_id);
CREATE INDEX IF NOT EXISTS idx_crm_opportunities_stage ON public.crm_opportunities(stage);
CREATE INDEX IF NOT EXISTS idx_crm_opportunities_created_at ON public.crm_opportunities(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_invoices_customer_id ON public.invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON public.invoices(status);
CREATE INDEX IF NOT EXISTS idx_invoices_load_id ON public.invoices(load_id);

CREATE INDEX IF NOT EXISTS idx_agent_commissions_agent_id ON public.agent_commissions(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_commissions_load_id ON public.agent_commissions(load_id);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON public.activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_entity ON public.activity_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON public.activity_logs(created_at DESC);

-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================

ALTER TABLE public.tms_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tms_carriers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tms_agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_opportunities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_commissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receivables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_performance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tms_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tms_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- Admin-only policies
DROP POLICY IF EXISTS "Admin Full Access - Customers" ON public.tms_customers;
CREATE POLICY "Admin Full Access - Customers" ON public.tms_customers FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Carriers" ON public.tms_carriers;
CREATE POLICY "Admin Full Access - Carriers" ON public.tms_carriers FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Agents" ON public.tms_agents;
CREATE POLICY "Admin Full Access - Agents" ON public.tms_agents FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Loads" ON public.loads;
CREATE POLICY "Admin Full Access - Loads" ON public.loads FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - CRM Opportunities" ON public.crm_opportunities;
CREATE POLICY "Admin Full Access - CRM Opportunities" ON public.crm_opportunities FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - CRM Activities" ON public.crm_activities;
CREATE POLICY "Admin Full Access - CRM Activities" ON public.crm_activities FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Invoices" ON public.invoices;
CREATE POLICY "Admin Full Access - Invoices" ON public.invoices FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Payments" ON public.payments;
CREATE POLICY "Admin Full Access - Payments" ON public.payments FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Commissions" ON public.agent_commissions;
CREATE POLICY "Admin Full Access - Commissions" ON public.agent_commissions FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Receivables" ON public.receivables;
CREATE POLICY "Admin Full Access - Receivables" ON public.receivables FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Expenses" ON public.expenses;
CREATE POLICY "Admin Full Access - Expenses" ON public.expenses FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Agent Performance" ON public.agent_performance;
CREATE POLICY "Admin Full Access - Agent Performance" ON public.agent_performance FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Agent Goals" ON public.agent_goals;
CREATE POLICY "Admin Full Access - Agent Goals" ON public.agent_goals FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - TMS Users" ON public.tms_users;
CREATE POLICY "Admin Full Access - TMS Users" ON public.tms_users FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Settings" ON public.tms_settings;
CREATE POLICY "Admin Full Access - Settings" ON public.tms_settings FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

DROP POLICY IF EXISTS "Admin Full Access - Activity Logs" ON public.activity_logs;
CREATE POLICY "Admin Full Access - Activity Logs" ON public.activity_logs FOR ALL TO authenticated USING (auth.jwt() ->> 'email' = 'ozan@loyalbrokerage.com');

-- =====================================================
-- HELPER FUNCTIONS
-- =====================================================

CREATE OR REPLACE FUNCTION public.generate_load_id()
RETURNS TEXT LANGUAGE plpgsql AS $$
DECLARE
    year INTEGER;
    max_num INTEGER;
    next_num TEXT;
BEGIN
    year := EXTRACT(YEAR FROM NOW());
    SELECT COALESCE(MAX(CAST(SPLIT_PART(id, '-', 3) AS INTEGER)), 0) INTO max_num FROM public.loads WHERE id LIKE 'L-' || year || '-%';
    next_num := LPAD((max_num + 1)::TEXT, 4, '0');
    RETURN 'L-' || year || '-' || next_num;
END;
$$;

CREATE OR REPLACE FUNCTION public.generate_opportunity_id()
RETURNS TEXT LANGUAGE plpgsql AS $$
DECLARE
    max_num INTEGER;
    next_num TEXT;
BEGIN
    SELECT COALESCE(MAX(CAST(SUBSTRING(id FROM 5) AS INTEGER)), 0) INTO max_num FROM public.crm_opportunities WHERE id LIKE 'OPP-%';
    next_num := LPAD((max_num + 1)::TEXT, 3, '0');
    RETURN 'OPP-' || next_num;
END;
$$;

CREATE OR REPLACE FUNCTION public.generate_invoice_id()
RETURNS TEXT LANGUAGE plpgsql AS $$
DECLARE
    max_num INTEGER;
    next_num TEXT;
BEGIN
    SELECT COALESCE(MAX(CAST(SUBSTRING(id FROM 5) AS INTEGER)), 0) INTO max_num FROM public.invoices WHERE id LIKE 'INV-%';
    next_num := LPAD((max_num + 1)::TEXT, 3, '0');
    RETURN 'INV-' || next_num;
END;
$$;

-- =====================================================
-- SAMPLE DATA
-- =====================================================

INSERT INTO public.tms_agents (id, name, email, phone, commission_rate, hire_date) VALUES
(1, 'Ozan Akdemir', 'ozan@loyalbrokerage.com', '555-0100', 10.00, '2023-01-15'),
(2, 'Jane Smith', 'jane@loyalbrokerage.com', '555-0101', 10.00, '2023-03-20'),
(3, 'David Lopez', 'david@loyalbrokerage.com', '555-0102', 10.00, '2023-06-10')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tms_customers (id, name, contact_name, email, phone, address, payment_terms, avg_rate) VALUES
(1, 'ABC Manufacturing', 'John Smith', 'john@abcmfg.com', '555-0201', '1234 Industrial Pkwy, Chicago, IL', 'Net 30', 2500.00),
(2, 'Max Steel Inc', 'Sarah Johnson', 'sarah@maxsteel.com', '555-0202', '789 Steel Ave, Pittsburgh, PA', 'Net 45', 2350.00),
(3, 'Global Trade Solutions', 'Mike Chen', 'mike@globaltrade.com', '555-0203', '456 Port St, Los Angeles, CA', 'Net 30', 2600.00),
(4, 'Metro Freight Services', 'Alex Turner', 'alex@metrofreight.com', '555-0204', '321 Logistics Blvd, Dallas, TX', 'Net 30', 2300.00),
(5, 'City Logistics Hub', 'Maria Garcia', 'maria@citylogistics.com', '555-0205', '654 Transport Way, Miami, FL', 'Net 60', 2450.00)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tms_carriers (id, name, mc_number, dot_number, contact_name, email, phone, insurance_expiry, status) VALUES
(1, 'Ada Fleet LLC', 'MC123456', 'DOT789012', 'Tom Wilson', 'dispatch@adafleet.com', '555-0301', '2025-12-31', 'Active'),
(2, 'Swift Carriers', 'MC234567', 'DOT890123', 'Linda Garcia', 'ops@swiftcarriers.com', '555-0302', '2025-10-15', 'Active'),
(3, 'Reliable Transport', 'MC345678', 'DOT901234', 'Bob Anderson', 'dispatch@reliabletrans.com', '555-0303', '2025-11-30', 'Active'),
(4, 'National Freight', 'MC456789', 'DOT012345', 'Chris Johnson', 'ops@nationalfreight.com', '555-0304', '2026-01-15', 'Active'),
(5, 'Central Carriers', 'MC567890', 'DOT123456', 'Pat Martinez', 'dispatch@centralcarriers.com', '555-0305', '2025-08-20', 'Active')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.crm_opportunities (id, customer_name, contact_email, stage, estimated_rate, agent_id, agent_name, created_at) VALUES
('OPP-001', 'ABC Manufacturing', 'john@abcmfg.com', 'Customer', 2000, 2, 'Jane Smith', '2024-11-15'),
('OPP-002', 'Max Steel Inc', 'fred@maxsteel.com', 'Lead', NULL, 1, 'Ozan Akdemir', '2024-11-20'),
('OPP-003', 'Global Trade Solutions', 'contact@globaltrade.com', 'Qualified', 1500, 2, 'Jane Smith', '2024-11-18'),
('OPP-004', 'Metro Freight Services', 'alex@metrofreight.com', 'Repeat', 2500, 3, 'David Lopez', '2024-10-05'),
('OPP-005', 'City Logistics Hub', 'maria@citylogistics.com', 'Prospect', NULL, 3, 'David Lopez', '2024-11-25')
ON CONFLICT (id) DO NOTHING;
