create extension if not exists "http" with schema "public";


  create table "public"."activity_logs" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid,
    "entity_type" text not null,
    "entity_id" text not null,
    "action" text not null,
    "changes" jsonb,
    "ip_address" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."activity_logs" enable row level security;


  create table "public"."agent_commissions" (
    "id" bigint generated by default as identity not null,
    "load_id" text,
    "agent_id" bigint,
    "agent_name" text,
    "gross_profit" numeric(10,2) not null,
    "commission_rate" numeric(5,2) not null,
    "commission_amount" numeric(10,2) not null,
    "status" text default 'Pending'::text,
    "paid_date" date,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."agent_commissions" enable row level security;


  create table "public"."agent_goals" (
    "id" bigint generated by default as identity not null,
    "agent_id" bigint,
    "goal_type" text,
    "target_value" numeric(10,2) not null,
    "period" text,
    "start_date" date not null,
    "end_date" date not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."agent_goals" enable row level security;


  create table "public"."agent_performance" (
    "id" bigint generated by default as identity not null,
    "agent_id" bigint,
    "period_start" date not null,
    "period_end" date not null,
    "loads_closed" integer default 0,
    "revenue" numeric(10,2) default 0,
    "profit" numeric(10,2) default 0,
    "commission" numeric(10,2) default 0,
    "conversion_rate" numeric(5,2),
    "created_at" timestamp with time zone default now()
      );


alter table "public"."agent_performance" enable row level security;


  create table "public"."carrier_applications" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone default now(),
    "company_name" text,
    "dba" text,
    "business_type" text,
    "address_street" text,
    "address_city" text,
    "address_state" text,
    "address_zip" text,
    "mc_number" text,
    "dot_number" text,
    "ein" text,
    "years_in_business" text,
    "primary_contact" text,
    "primary_phone" text,
    "primary_email" text,
    "dispatch_contact" text,
    "dispatch_phone" text,
    "billing_email" text,
    "after_hours_phone" text,
    "truck_count" text,
    "driver_count" text,
    "equipment_types" text[],
    "operating_states" text[],
    "hazmat" boolean,
    "safety_rating" text,
    "liability_amount" text,
    "cargo_amount" text,
    "insurance_company" text,
    "agent_name" text,
    "agent_email" text,
    "agent_phone" text,
    "policy_expiration" date,
    "w9_url" text,
    "coi_url" text,
    "insurance_doc_url" text,
    "authority_letter_url" text,
    "agreement_url" text,
    "ach_url" text,
    "compliance_1" boolean,
    "compliance_2" boolean,
    "compliance_3" boolean,
    "compliance_4" boolean,
    "status" text default 'pending'::text,
    "cargo_coverage" text,
    "primary_contact_name" text,
    "dispatch_contact_name" text,
    "number_of_trucks" integer,
    "number_of_drivers" integer,
    "equipment_dryvan" boolean,
    "equipment_reefer" boolean,
    "equipment_flatbed" boolean,
    "equipment_stepdeck" boolean,
    "equipment_power_only" boolean,
    "hazmat_certified" boolean,
    "liability_coverage" text,
    "mc_authority_letter_url" text,
    "signed_carrier_agreement_url" text,
    "ach_voided_check_url" text,
    "agreed_all_info_correct" boolean,
    "agreed_insurance_verification" boolean,
    "agreed_fmcsa_rules" boolean,
    "agreed_llc_carrier_terms" boolean
      );


alter table "public"."carrier_applications" enable row level security;


  create table "public"."crm_activities" (
    "id" bigint generated by default as identity not null,
    "opportunity_id" text,
    "activity_type" text,
    "description" text not null,
    "agent_id" bigint,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."crm_activities" enable row level security;


  create table "public"."crm_opportunities" (
    "id" text not null,
    "customer_name" text not null,
    "contact_email" text,
    "contact_phone" text,
    "company_name" text,
    "carrier_name" text,
    "load_id" text,
    "stage" text default 'Prospect'::text,
    "estimated_rate" numeric(10,2),
    "agent_id" bigint,
    "agent_name" text,
    "notes" text,
    "next_follow_up" date,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."crm_opportunities" enable row level security;


  create table "public"."expenses" (
    "id" bigint generated by default as identity not null,
    "category" text not null,
    "description" text not null,
    "amount" numeric(10,2) not null,
    "truck" text,
    "expense_date" date default CURRENT_DATE,
    "receipt_url" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."expenses" enable row level security;


  create table "public"."invoices" (
    "id" text not null,
    "load_id" text,
    "customer_id" bigint,
    "customer_name" text,
    "amount" numeric(10,2) not null,
    "status" text default 'Pending'::text,
    "date_sent" date default CURRENT_DATE,
    "date_paid" date,
    "due_date" date,
    "notes" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."invoices" enable row level security;


  create table "public"."loads" (
    "id" text not null,
    "customer_id" bigint,
    "customer_name" text,
    "carrier_id" bigint,
    "carrier_name" text,
    "agent_id" bigint,
    "agent_name" text,
    "pickup_address" text not null,
    "delivery_address" text not null,
    "rate" numeric(10,2) not null,
    "carrier_cost" numeric(10,2) not null default 0,
    "trip_distance" integer,
    "equipment_type" text,
    "status" text default 'Pending'::text,
    "reference_number" text,
    "notes" text,
    "appointment_date" date,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."loads" enable row level security;


  create table "public"."payments" (
    "id" bigint generated by default as identity not null,
    "invoice_id" text,
    "amount" numeric(10,2) not null,
    "payment_date" date default CURRENT_DATE,
    "payment_method" text,
    "reference_number" text,
    "notes" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."payments" enable row level security;


  create table "public"."quotes" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp without time zone default now(),
    "company_name" text,
    "contact_name" text,
    "email" text,
    "phone" text,
    "pickup_city" text,
    "pickup_state" text,
    "delivery_city" text,
    "delivery_state" text,
    "pickup_date" date,
    "delivery_date" date,
    "equipment_type" text,
    "commodity" text,
    "weight" text,
    "pallets" text,
    "special_notes" text,
    "attachment_url" text
      );



  create table "public"."receivables" (
    "id" bigint generated by default as identity not null,
    "invoice_id" text,
    "customer_id" bigint,
    "customer_name" text,
    "due_amount" numeric(10,2) not null,
    "days_outstanding" integer,
    "status" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."receivables" enable row level security;


  create table "public"."tms_agents" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "email" text not null,
    "phone" text,
    "commission_rate" numeric(5,2) default 10.00,
    "hire_date" date default CURRENT_DATE,
    "status" text default 'Active'::text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."tms_agents" enable row level security;


  create table "public"."tms_carriers" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "mc_number" text,
    "dot_number" text,
    "contact_name" text,
    "email" text,
    "phone" text,
    "insurance_expiry" date,
    "credit_status" text default 'Approved'::text,
    "status" text default 'Active'::text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."tms_carriers" enable row level security;


  create table "public"."tms_customers" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "contact_name" text,
    "email" text,
    "phone" text,
    "address" text,
    "payment_terms" text default 'Net 30'::text,
    "credit_status" text default 'Approved'::text,
    "avg_rate" numeric(10,2),
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."tms_customers" enable row level security;


  create table "public"."tms_settings" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid,
    "setting_key" text not null,
    "setting_value" jsonb,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."tms_settings" enable row level security;


  create table "public"."tms_users" (
    "id" uuid not null,
    "email" text not null,
    "full_name" text,
    "role" text default 'agent'::text,
    "agent_id" bigint,
    "is_active" boolean default true,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."tms_users" enable row level security;

CREATE UNIQUE INDEX activity_logs_pkey ON public.activity_logs USING btree (id);

CREATE UNIQUE INDEX agent_commissions_pkey ON public.agent_commissions USING btree (id);

CREATE UNIQUE INDEX agent_goals_pkey ON public.agent_goals USING btree (id);

CREATE UNIQUE INDEX agent_performance_agent_id_period_start_period_end_key ON public.agent_performance USING btree (agent_id, period_start, period_end);

CREATE UNIQUE INDEX agent_performance_pkey ON public.agent_performance USING btree (id);

CREATE UNIQUE INDEX carrier_applications_pkey ON public.carrier_applications USING btree (id);

CREATE UNIQUE INDEX crm_activities_pkey ON public.crm_activities USING btree (id);

CREATE UNIQUE INDEX crm_opportunities_pkey ON public.crm_opportunities USING btree (id);

CREATE UNIQUE INDEX expenses_pkey ON public.expenses USING btree (id);

CREATE INDEX idx_activity_logs_created_at ON public.activity_logs USING btree (created_at DESC);

CREATE INDEX idx_activity_logs_entity ON public.activity_logs USING btree (entity_type, entity_id);

CREATE INDEX idx_activity_logs_user_id ON public.activity_logs USING btree (user_id);

CREATE INDEX idx_agent_commissions_agent_id ON public.agent_commissions USING btree (agent_id);

CREATE INDEX idx_agent_commissions_load_id ON public.agent_commissions USING btree (load_id);

CREATE INDEX idx_crm_opportunities_agent_id ON public.crm_opportunities USING btree (agent_id);

CREATE INDEX idx_crm_opportunities_created_at ON public.crm_opportunities USING btree (created_at DESC);

CREATE INDEX idx_crm_opportunities_stage ON public.crm_opportunities USING btree (stage);

CREATE INDEX idx_invoices_customer_id ON public.invoices USING btree (customer_id);

CREATE INDEX idx_invoices_load_id ON public.invoices USING btree (load_id);

CREATE INDEX idx_invoices_status ON public.invoices USING btree (status);

CREATE INDEX idx_loads_agent_id ON public.loads USING btree (agent_id);

CREATE INDEX idx_loads_carrier_id ON public.loads USING btree (carrier_id);

CREATE INDEX idx_loads_created_at ON public.loads USING btree (created_at DESC);

CREATE INDEX idx_loads_customer_id ON public.loads USING btree (customer_id);

CREATE INDEX idx_loads_status ON public.loads USING btree (status);

CREATE UNIQUE INDEX invoices_pkey ON public.invoices USING btree (id);

CREATE UNIQUE INDEX loads_pkey ON public.loads USING btree (id);

CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (id);

CREATE UNIQUE INDEX quotes_pkey ON public.quotes USING btree (id);

CREATE UNIQUE INDEX receivables_pkey ON public.receivables USING btree (id);

CREATE UNIQUE INDEX tms_agents_email_key ON public.tms_agents USING btree (email);

CREATE UNIQUE INDEX tms_agents_pkey ON public.tms_agents USING btree (id);

CREATE UNIQUE INDEX tms_carriers_mc_number_key ON public.tms_carriers USING btree (mc_number);

CREATE UNIQUE INDEX tms_carriers_pkey ON public.tms_carriers USING btree (id);

CREATE UNIQUE INDEX tms_customers_pkey ON public.tms_customers USING btree (id);

CREATE UNIQUE INDEX tms_settings_pkey ON public.tms_settings USING btree (id);

CREATE UNIQUE INDEX tms_settings_user_id_setting_key_key ON public.tms_settings USING btree (user_id, setting_key);

CREATE UNIQUE INDEX tms_users_email_key ON public.tms_users USING btree (email);

CREATE UNIQUE INDEX tms_users_pkey ON public.tms_users USING btree (id);

alter table "public"."activity_logs" add constraint "activity_logs_pkey" PRIMARY KEY using index "activity_logs_pkey";

alter table "public"."agent_commissions" add constraint "agent_commissions_pkey" PRIMARY KEY using index "agent_commissions_pkey";

alter table "public"."agent_goals" add constraint "agent_goals_pkey" PRIMARY KEY using index "agent_goals_pkey";

alter table "public"."agent_performance" add constraint "agent_performance_pkey" PRIMARY KEY using index "agent_performance_pkey";

alter table "public"."carrier_applications" add constraint "carrier_applications_pkey" PRIMARY KEY using index "carrier_applications_pkey";

alter table "public"."crm_activities" add constraint "crm_activities_pkey" PRIMARY KEY using index "crm_activities_pkey";

alter table "public"."crm_opportunities" add constraint "crm_opportunities_pkey" PRIMARY KEY using index "crm_opportunities_pkey";

alter table "public"."expenses" add constraint "expenses_pkey" PRIMARY KEY using index "expenses_pkey";

alter table "public"."invoices" add constraint "invoices_pkey" PRIMARY KEY using index "invoices_pkey";

alter table "public"."loads" add constraint "loads_pkey" PRIMARY KEY using index "loads_pkey";

alter table "public"."payments" add constraint "payments_pkey" PRIMARY KEY using index "payments_pkey";

alter table "public"."quotes" add constraint "quotes_pkey" PRIMARY KEY using index "quotes_pkey";

alter table "public"."receivables" add constraint "receivables_pkey" PRIMARY KEY using index "receivables_pkey";

alter table "public"."tms_agents" add constraint "tms_agents_pkey" PRIMARY KEY using index "tms_agents_pkey";

alter table "public"."tms_carriers" add constraint "tms_carriers_pkey" PRIMARY KEY using index "tms_carriers_pkey";

alter table "public"."tms_customers" add constraint "tms_customers_pkey" PRIMARY KEY using index "tms_customers_pkey";

alter table "public"."tms_settings" add constraint "tms_settings_pkey" PRIMARY KEY using index "tms_settings_pkey";

alter table "public"."tms_users" add constraint "tms_users_pkey" PRIMARY KEY using index "tms_users_pkey";

alter table "public"."activity_logs" add constraint "activity_logs_action_check" CHECK ((action = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text, 'view'::text]))) not valid;

alter table "public"."activity_logs" validate constraint "activity_logs_action_check";

alter table "public"."activity_logs" add constraint "activity_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."activity_logs" validate constraint "activity_logs_user_id_fkey";

alter table "public"."agent_commissions" add constraint "agent_commissions_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES public.tms_agents(id) ON DELETE CASCADE not valid;

alter table "public"."agent_commissions" validate constraint "agent_commissions_agent_id_fkey";

alter table "public"."agent_commissions" add constraint "agent_commissions_load_id_fkey" FOREIGN KEY (load_id) REFERENCES public.loads(id) ON DELETE CASCADE not valid;

alter table "public"."agent_commissions" validate constraint "agent_commissions_load_id_fkey";

alter table "public"."agent_commissions" add constraint "agent_commissions_status_check" CHECK ((status = ANY (ARRAY['Pending'::text, 'Paid'::text]))) not valid;

alter table "public"."agent_commissions" validate constraint "agent_commissions_status_check";

alter table "public"."agent_goals" add constraint "agent_goals_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES public.tms_agents(id) ON DELETE CASCADE not valid;

alter table "public"."agent_goals" validate constraint "agent_goals_agent_id_fkey";

alter table "public"."agent_goals" add constraint "agent_goals_goal_type_check" CHECK ((goal_type = ANY (ARRAY['Revenue'::text, 'Loads'::text, 'Profit'::text, 'Commission'::text]))) not valid;

alter table "public"."agent_goals" validate constraint "agent_goals_goal_type_check";

alter table "public"."agent_goals" add constraint "agent_goals_period_check" CHECK ((period = ANY (ARRAY['Weekly'::text, 'Monthly'::text, 'Quarterly'::text, 'Yearly'::text]))) not valid;

alter table "public"."agent_goals" validate constraint "agent_goals_period_check";

alter table "public"."agent_performance" add constraint "agent_performance_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES public.tms_agents(id) ON DELETE CASCADE not valid;

alter table "public"."agent_performance" validate constraint "agent_performance_agent_id_fkey";

alter table "public"."agent_performance" add constraint "agent_performance_agent_id_period_start_period_end_key" UNIQUE using index "agent_performance_agent_id_period_start_period_end_key";

alter table "public"."crm_activities" add constraint "crm_activities_activity_type_check" CHECK ((activity_type = ANY (ARRAY['Call'::text, 'Email'::text, 'Meeting'::text, 'Note'::text]))) not valid;

alter table "public"."crm_activities" validate constraint "crm_activities_activity_type_check";

alter table "public"."crm_activities" add constraint "crm_activities_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES public.tms_agents(id) ON DELETE SET NULL not valid;

alter table "public"."crm_activities" validate constraint "crm_activities_agent_id_fkey";

alter table "public"."crm_activities" add constraint "crm_activities_opportunity_id_fkey" FOREIGN KEY (opportunity_id) REFERENCES public.crm_opportunities(id) ON DELETE CASCADE not valid;

alter table "public"."crm_activities" validate constraint "crm_activities_opportunity_id_fkey";

alter table "public"."crm_opportunities" add constraint "crm_opportunities_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES public.tms_agents(id) ON DELETE SET NULL not valid;

alter table "public"."crm_opportunities" validate constraint "crm_opportunities_agent_id_fkey";

alter table "public"."crm_opportunities" add constraint "crm_opportunities_load_id_fkey" FOREIGN KEY (load_id) REFERENCES public.loads(id) ON DELETE SET NULL not valid;

alter table "public"."crm_opportunities" validate constraint "crm_opportunities_load_id_fkey";

alter table "public"."crm_opportunities" add constraint "crm_opportunities_stage_check" CHECK ((stage = ANY (ARRAY['Prospect'::text, 'Lead'::text, 'Qualified'::text, 'Customer'::text, 'Repeat'::text]))) not valid;

alter table "public"."crm_opportunities" validate constraint "crm_opportunities_stage_check";

alter table "public"."expenses" add constraint "expenses_category_check" CHECK ((category = ANY (ARRAY['Fuel'::text, 'Maintenance'::text, 'Dispatch'::text, 'Insurance'::text, 'Other'::text]))) not valid;

alter table "public"."expenses" validate constraint "expenses_category_check";

alter table "public"."invoices" add constraint "invoices_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public.tms_customers(id) ON DELETE SET NULL not valid;

alter table "public"."invoices" validate constraint "invoices_customer_id_fkey";

alter table "public"."invoices" add constraint "invoices_load_id_fkey" FOREIGN KEY (load_id) REFERENCES public.loads(id) ON DELETE SET NULL not valid;

alter table "public"."invoices" validate constraint "invoices_load_id_fkey";

alter table "public"."invoices" add constraint "invoices_status_check" CHECK ((status = ANY (ARRAY['Pending'::text, 'Paid'::text, 'Overdue'::text, 'Cancelled'::text]))) not valid;

alter table "public"."invoices" validate constraint "invoices_status_check";

alter table "public"."loads" add constraint "loads_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES public.tms_agents(id) ON DELETE SET NULL not valid;

alter table "public"."loads" validate constraint "loads_agent_id_fkey";

alter table "public"."loads" add constraint "loads_carrier_id_fkey" FOREIGN KEY (carrier_id) REFERENCES public.tms_carriers(id) ON DELETE SET NULL not valid;

alter table "public"."loads" validate constraint "loads_carrier_id_fkey";

alter table "public"."loads" add constraint "loads_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public.tms_customers(id) ON DELETE SET NULL not valid;

alter table "public"."loads" validate constraint "loads_customer_id_fkey";

alter table "public"."loads" add constraint "loads_equipment_type_check" CHECK ((equipment_type = ANY (ARRAY['Dry Van'::text, 'Reefer'::text, 'Flatbed'::text, 'Power Only'::text]))) not valid;

alter table "public"."loads" validate constraint "loads_equipment_type_check";

alter table "public"."loads" add constraint "loads_status_check" CHECK ((status = ANY (ARRAY['Pending'::text, 'Booked'::text, 'Delivered'::text, 'Cancelled'::text]))) not valid;

alter table "public"."loads" validate constraint "loads_status_check";

alter table "public"."payments" add constraint "payments_invoice_id_fkey" FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE SET NULL not valid;

alter table "public"."payments" validate constraint "payments_invoice_id_fkey";

alter table "public"."payments" add constraint "payments_payment_method_check" CHECK ((payment_method = ANY (ARRAY['ACH'::text, 'Wire'::text, 'Check'::text, 'Credit Card'::text]))) not valid;

alter table "public"."payments" validate constraint "payments_payment_method_check";

alter table "public"."receivables" add constraint "receivables_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public.tms_customers(id) ON DELETE SET NULL not valid;

alter table "public"."receivables" validate constraint "receivables_customer_id_fkey";

alter table "public"."receivables" add constraint "receivables_invoice_id_fkey" FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE not valid;

alter table "public"."receivables" validate constraint "receivables_invoice_id_fkey";

alter table "public"."receivables" add constraint "receivables_status_check" CHECK ((status = ANY (ARRAY['Current'::text, 'Overdue'::text]))) not valid;

alter table "public"."receivables" validate constraint "receivables_status_check";

alter table "public"."tms_agents" add constraint "tms_agents_email_key" UNIQUE using index "tms_agents_email_key";

alter table "public"."tms_agents" add constraint "tms_agents_status_check" CHECK ((status = ANY (ARRAY['Active'::text, 'Inactive'::text]))) not valid;

alter table "public"."tms_agents" validate constraint "tms_agents_status_check";

alter table "public"."tms_carriers" add constraint "tms_carriers_credit_status_check" CHECK ((credit_status = ANY (ARRAY['Approved'::text, 'Review'::text, 'Denied'::text]))) not valid;

alter table "public"."tms_carriers" validate constraint "tms_carriers_credit_status_check";

alter table "public"."tms_carriers" add constraint "tms_carriers_mc_number_key" UNIQUE using index "tms_carriers_mc_number_key";

alter table "public"."tms_carriers" add constraint "tms_carriers_status_check" CHECK ((status = ANY (ARRAY['Active'::text, 'Inactive'::text, 'Pending'::text]))) not valid;

alter table "public"."tms_carriers" validate constraint "tms_carriers_status_check";

alter table "public"."tms_customers" add constraint "tms_customers_credit_status_check" CHECK ((credit_status = ANY (ARRAY['Approved'::text, 'Review'::text, 'Denied'::text]))) not valid;

alter table "public"."tms_customers" validate constraint "tms_customers_credit_status_check";

alter table "public"."tms_settings" add constraint "tms_settings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."tms_settings" validate constraint "tms_settings_user_id_fkey";

alter table "public"."tms_settings" add constraint "tms_settings_user_id_setting_key_key" UNIQUE using index "tms_settings_user_id_setting_key_key";

alter table "public"."tms_users" add constraint "tms_users_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES public.tms_agents(id) ON DELETE SET NULL not valid;

alter table "public"."tms_users" validate constraint "tms_users_agent_id_fkey";

alter table "public"."tms_users" add constraint "tms_users_email_key" UNIQUE using index "tms_users_email_key";

alter table "public"."tms_users" add constraint "tms_users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."tms_users" validate constraint "tms_users_id_fkey";

alter table "public"."tms_users" add constraint "tms_users_role_check" CHECK ((role = ANY (ARRAY['admin'::text, 'agent'::text, 'dispatcher'::text, 'accountant'::text]))) not valid;

alter table "public"."tms_users" validate constraint "tms_users_role_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.generate_invoice_id()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    max_num INTEGER;
    next_num TEXT;
BEGIN
    SELECT COALESCE(MAX(CAST(SUBSTRING(id FROM 5) AS INTEGER)), 0) INTO max_num FROM public.invoices WHERE id LIKE 'INV-%';
    next_num := LPAD((max_num + 1)::TEXT, 3, '0');
    RETURN 'INV-' || next_num;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.generate_load_id()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    year INTEGER;
    max_num INTEGER;
    next_num TEXT;
BEGIN
    year := EXTRACT(YEAR FROM NOW());
    SELECT COALESCE(MAX(CAST(SPLIT_PART(id, '-', 3) AS INTEGER)), 0) INTO max_num FROM public.loads WHERE id LIKE 'L-' || year || '-%';
    next_num := LPAD((max_num + 1)::TEXT, 4, '0');
    RETURN 'L-' || year || '-' || next_num;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.generate_opportunity_id()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    max_num INTEGER;
    next_num TEXT;
BEGIN
    SELECT COALESCE(MAX(CAST(SUBSTRING(id FROM 5) AS INTEGER)), 0) INTO max_num FROM public.crm_opportunities WHERE id LIKE 'OPP-%';
    next_num := LPAD((max_num + 1)::TEXT, 3, '0');
    RETURN 'OPP-' || next_num;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_carrier_signup()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  perform
    net.http_post(
      url := 'https://cfcrttsxeaugwfuoirod.supabase.co/functions/v1/carrier-signup-email',
      headers := jsonb_build_object(
        'Content-Type', 'application/json'
      ),
      body := jsonb_build_object(
        'record', row_to_json(NEW)
      )
    );
  return NEW;
end;
$function$
;

create type "public"."http_header" as ("field" character varying, "value" character varying);

create type "public"."http_request" as ("method" public.http_method, "uri" character varying, "headers" public.http_header[], "content_type" character varying, "content" character varying);

create type "public"."http_response" as ("status" integer, "content_type" character varying, "headers" public.http_header[], "content" character varying);

CREATE OR REPLACE FUNCTION public.trigger_carrier_signup_email()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  request_id bigint;
BEGIN
  -- Use pg_net to send POST request
  SELECT net.http_post(
       url := 'https://cfcrttsxeaugwfuoirod.supabase.co/functions/v1/carrier-signup-email',
       headers := jsonb_build_object('Content-Type','application/json', 'Authorization', 'Bearer ' || current_setting('request.jwt.claim.role', true)),
       body := jsonb_build_object('record', row_to_json(NEW))
   ) INTO request_id;
   
  RETURN NEW;
END;
$function$
;

grant delete on table "public"."activity_logs" to "anon";

grant insert on table "public"."activity_logs" to "anon";

grant references on table "public"."activity_logs" to "anon";

grant select on table "public"."activity_logs" to "anon";

grant trigger on table "public"."activity_logs" to "anon";

grant truncate on table "public"."activity_logs" to "anon";

grant update on table "public"."activity_logs" to "anon";

grant delete on table "public"."activity_logs" to "authenticated";

grant insert on table "public"."activity_logs" to "authenticated";

grant references on table "public"."activity_logs" to "authenticated";

grant select on table "public"."activity_logs" to "authenticated";

grant trigger on table "public"."activity_logs" to "authenticated";

grant truncate on table "public"."activity_logs" to "authenticated";

grant update on table "public"."activity_logs" to "authenticated";

grant delete on table "public"."activity_logs" to "service_role";

grant insert on table "public"."activity_logs" to "service_role";

grant references on table "public"."activity_logs" to "service_role";

grant select on table "public"."activity_logs" to "service_role";

grant trigger on table "public"."activity_logs" to "service_role";

grant truncate on table "public"."activity_logs" to "service_role";

grant update on table "public"."activity_logs" to "service_role";

grant delete on table "public"."agent_commissions" to "anon";

grant insert on table "public"."agent_commissions" to "anon";

grant references on table "public"."agent_commissions" to "anon";

grant select on table "public"."agent_commissions" to "anon";

grant trigger on table "public"."agent_commissions" to "anon";

grant truncate on table "public"."agent_commissions" to "anon";

grant update on table "public"."agent_commissions" to "anon";

grant delete on table "public"."agent_commissions" to "authenticated";

grant insert on table "public"."agent_commissions" to "authenticated";

grant references on table "public"."agent_commissions" to "authenticated";

grant select on table "public"."agent_commissions" to "authenticated";

grant trigger on table "public"."agent_commissions" to "authenticated";

grant truncate on table "public"."agent_commissions" to "authenticated";

grant update on table "public"."agent_commissions" to "authenticated";

grant delete on table "public"."agent_commissions" to "service_role";

grant insert on table "public"."agent_commissions" to "service_role";

grant references on table "public"."agent_commissions" to "service_role";

grant select on table "public"."agent_commissions" to "service_role";

grant trigger on table "public"."agent_commissions" to "service_role";

grant truncate on table "public"."agent_commissions" to "service_role";

grant update on table "public"."agent_commissions" to "service_role";

grant delete on table "public"."agent_goals" to "anon";

grant insert on table "public"."agent_goals" to "anon";

grant references on table "public"."agent_goals" to "anon";

grant select on table "public"."agent_goals" to "anon";

grant trigger on table "public"."agent_goals" to "anon";

grant truncate on table "public"."agent_goals" to "anon";

grant update on table "public"."agent_goals" to "anon";

grant delete on table "public"."agent_goals" to "authenticated";

grant insert on table "public"."agent_goals" to "authenticated";

grant references on table "public"."agent_goals" to "authenticated";

grant select on table "public"."agent_goals" to "authenticated";

grant trigger on table "public"."agent_goals" to "authenticated";

grant truncate on table "public"."agent_goals" to "authenticated";

grant update on table "public"."agent_goals" to "authenticated";

grant delete on table "public"."agent_goals" to "service_role";

grant insert on table "public"."agent_goals" to "service_role";

grant references on table "public"."agent_goals" to "service_role";

grant select on table "public"."agent_goals" to "service_role";

grant trigger on table "public"."agent_goals" to "service_role";

grant truncate on table "public"."agent_goals" to "service_role";

grant update on table "public"."agent_goals" to "service_role";

grant delete on table "public"."agent_performance" to "anon";

grant insert on table "public"."agent_performance" to "anon";

grant references on table "public"."agent_performance" to "anon";

grant select on table "public"."agent_performance" to "anon";

grant trigger on table "public"."agent_performance" to "anon";

grant truncate on table "public"."agent_performance" to "anon";

grant update on table "public"."agent_performance" to "anon";

grant delete on table "public"."agent_performance" to "authenticated";

grant insert on table "public"."agent_performance" to "authenticated";

grant references on table "public"."agent_performance" to "authenticated";

grant select on table "public"."agent_performance" to "authenticated";

grant trigger on table "public"."agent_performance" to "authenticated";

grant truncate on table "public"."agent_performance" to "authenticated";

grant update on table "public"."agent_performance" to "authenticated";

grant delete on table "public"."agent_performance" to "service_role";

grant insert on table "public"."agent_performance" to "service_role";

grant references on table "public"."agent_performance" to "service_role";

grant select on table "public"."agent_performance" to "service_role";

grant trigger on table "public"."agent_performance" to "service_role";

grant truncate on table "public"."agent_performance" to "service_role";

grant update on table "public"."agent_performance" to "service_role";

grant delete on table "public"."carrier_applications" to "anon";

grant insert on table "public"."carrier_applications" to "anon";

grant references on table "public"."carrier_applications" to "anon";

grant select on table "public"."carrier_applications" to "anon";

grant trigger on table "public"."carrier_applications" to "anon";

grant truncate on table "public"."carrier_applications" to "anon";

grant update on table "public"."carrier_applications" to "anon";

grant delete on table "public"."carrier_applications" to "authenticated";

grant insert on table "public"."carrier_applications" to "authenticated";

grant references on table "public"."carrier_applications" to "authenticated";

grant select on table "public"."carrier_applications" to "authenticated";

grant trigger on table "public"."carrier_applications" to "authenticated";

grant truncate on table "public"."carrier_applications" to "authenticated";

grant update on table "public"."carrier_applications" to "authenticated";

grant delete on table "public"."carrier_applications" to "service_role";

grant insert on table "public"."carrier_applications" to "service_role";

grant references on table "public"."carrier_applications" to "service_role";

grant select on table "public"."carrier_applications" to "service_role";

grant trigger on table "public"."carrier_applications" to "service_role";

grant truncate on table "public"."carrier_applications" to "service_role";

grant update on table "public"."carrier_applications" to "service_role";

grant delete on table "public"."crm_activities" to "anon";

grant insert on table "public"."crm_activities" to "anon";

grant references on table "public"."crm_activities" to "anon";

grant select on table "public"."crm_activities" to "anon";

grant trigger on table "public"."crm_activities" to "anon";

grant truncate on table "public"."crm_activities" to "anon";

grant update on table "public"."crm_activities" to "anon";

grant delete on table "public"."crm_activities" to "authenticated";

grant insert on table "public"."crm_activities" to "authenticated";

grant references on table "public"."crm_activities" to "authenticated";

grant select on table "public"."crm_activities" to "authenticated";

grant trigger on table "public"."crm_activities" to "authenticated";

grant truncate on table "public"."crm_activities" to "authenticated";

grant update on table "public"."crm_activities" to "authenticated";

grant delete on table "public"."crm_activities" to "service_role";

grant insert on table "public"."crm_activities" to "service_role";

grant references on table "public"."crm_activities" to "service_role";

grant select on table "public"."crm_activities" to "service_role";

grant trigger on table "public"."crm_activities" to "service_role";

grant truncate on table "public"."crm_activities" to "service_role";

grant update on table "public"."crm_activities" to "service_role";

grant delete on table "public"."crm_opportunities" to "anon";

grant insert on table "public"."crm_opportunities" to "anon";

grant references on table "public"."crm_opportunities" to "anon";

grant select on table "public"."crm_opportunities" to "anon";

grant trigger on table "public"."crm_opportunities" to "anon";

grant truncate on table "public"."crm_opportunities" to "anon";

grant update on table "public"."crm_opportunities" to "anon";

grant delete on table "public"."crm_opportunities" to "authenticated";

grant insert on table "public"."crm_opportunities" to "authenticated";

grant references on table "public"."crm_opportunities" to "authenticated";

grant select on table "public"."crm_opportunities" to "authenticated";

grant trigger on table "public"."crm_opportunities" to "authenticated";

grant truncate on table "public"."crm_opportunities" to "authenticated";

grant update on table "public"."crm_opportunities" to "authenticated";

grant delete on table "public"."crm_opportunities" to "service_role";

grant insert on table "public"."crm_opportunities" to "service_role";

grant references on table "public"."crm_opportunities" to "service_role";

grant select on table "public"."crm_opportunities" to "service_role";

grant trigger on table "public"."crm_opportunities" to "service_role";

grant truncate on table "public"."crm_opportunities" to "service_role";

grant update on table "public"."crm_opportunities" to "service_role";

grant delete on table "public"."expenses" to "anon";

grant insert on table "public"."expenses" to "anon";

grant references on table "public"."expenses" to "anon";

grant select on table "public"."expenses" to "anon";

grant trigger on table "public"."expenses" to "anon";

grant truncate on table "public"."expenses" to "anon";

grant update on table "public"."expenses" to "anon";

grant delete on table "public"."expenses" to "authenticated";

grant insert on table "public"."expenses" to "authenticated";

grant references on table "public"."expenses" to "authenticated";

grant select on table "public"."expenses" to "authenticated";

grant trigger on table "public"."expenses" to "authenticated";

grant truncate on table "public"."expenses" to "authenticated";

grant update on table "public"."expenses" to "authenticated";

grant delete on table "public"."expenses" to "service_role";

grant insert on table "public"."expenses" to "service_role";

grant references on table "public"."expenses" to "service_role";

grant select on table "public"."expenses" to "service_role";

grant trigger on table "public"."expenses" to "service_role";

grant truncate on table "public"."expenses" to "service_role";

grant update on table "public"."expenses" to "service_role";

grant delete on table "public"."invoices" to "anon";

grant insert on table "public"."invoices" to "anon";

grant references on table "public"."invoices" to "anon";

grant select on table "public"."invoices" to "anon";

grant trigger on table "public"."invoices" to "anon";

grant truncate on table "public"."invoices" to "anon";

grant update on table "public"."invoices" to "anon";

grant delete on table "public"."invoices" to "authenticated";

grant insert on table "public"."invoices" to "authenticated";

grant references on table "public"."invoices" to "authenticated";

grant select on table "public"."invoices" to "authenticated";

grant trigger on table "public"."invoices" to "authenticated";

grant truncate on table "public"."invoices" to "authenticated";

grant update on table "public"."invoices" to "authenticated";

grant delete on table "public"."invoices" to "service_role";

grant insert on table "public"."invoices" to "service_role";

grant references on table "public"."invoices" to "service_role";

grant select on table "public"."invoices" to "service_role";

grant trigger on table "public"."invoices" to "service_role";

grant truncate on table "public"."invoices" to "service_role";

grant update on table "public"."invoices" to "service_role";

grant delete on table "public"."loads" to "anon";

grant insert on table "public"."loads" to "anon";

grant references on table "public"."loads" to "anon";

grant select on table "public"."loads" to "anon";

grant trigger on table "public"."loads" to "anon";

grant truncate on table "public"."loads" to "anon";

grant update on table "public"."loads" to "anon";

grant delete on table "public"."loads" to "authenticated";

grant insert on table "public"."loads" to "authenticated";

grant references on table "public"."loads" to "authenticated";

grant select on table "public"."loads" to "authenticated";

grant trigger on table "public"."loads" to "authenticated";

grant truncate on table "public"."loads" to "authenticated";

grant update on table "public"."loads" to "authenticated";

grant delete on table "public"."loads" to "service_role";

grant insert on table "public"."loads" to "service_role";

grant references on table "public"."loads" to "service_role";

grant select on table "public"."loads" to "service_role";

grant trigger on table "public"."loads" to "service_role";

grant truncate on table "public"."loads" to "service_role";

grant update on table "public"."loads" to "service_role";

grant delete on table "public"."payments" to "anon";

grant insert on table "public"."payments" to "anon";

grant references on table "public"."payments" to "anon";

grant select on table "public"."payments" to "anon";

grant trigger on table "public"."payments" to "anon";

grant truncate on table "public"."payments" to "anon";

grant update on table "public"."payments" to "anon";

grant delete on table "public"."payments" to "authenticated";

grant insert on table "public"."payments" to "authenticated";

grant references on table "public"."payments" to "authenticated";

grant select on table "public"."payments" to "authenticated";

grant trigger on table "public"."payments" to "authenticated";

grant truncate on table "public"."payments" to "authenticated";

grant update on table "public"."payments" to "authenticated";

grant delete on table "public"."payments" to "service_role";

grant insert on table "public"."payments" to "service_role";

grant references on table "public"."payments" to "service_role";

grant select on table "public"."payments" to "service_role";

grant trigger on table "public"."payments" to "service_role";

grant truncate on table "public"."payments" to "service_role";

grant update on table "public"."payments" to "service_role";

grant delete on table "public"."quotes" to "anon";

grant insert on table "public"."quotes" to "anon";

grant references on table "public"."quotes" to "anon";

grant select on table "public"."quotes" to "anon";

grant trigger on table "public"."quotes" to "anon";

grant truncate on table "public"."quotes" to "anon";

grant update on table "public"."quotes" to "anon";

grant delete on table "public"."quotes" to "authenticated";

grant insert on table "public"."quotes" to "authenticated";

grant references on table "public"."quotes" to "authenticated";

grant select on table "public"."quotes" to "authenticated";

grant trigger on table "public"."quotes" to "authenticated";

grant truncate on table "public"."quotes" to "authenticated";

grant update on table "public"."quotes" to "authenticated";

grant delete on table "public"."quotes" to "service_role";

grant insert on table "public"."quotes" to "service_role";

grant references on table "public"."quotes" to "service_role";

grant select on table "public"."quotes" to "service_role";

grant trigger on table "public"."quotes" to "service_role";

grant truncate on table "public"."quotes" to "service_role";

grant update on table "public"."quotes" to "service_role";

grant delete on table "public"."receivables" to "anon";

grant insert on table "public"."receivables" to "anon";

grant references on table "public"."receivables" to "anon";

grant select on table "public"."receivables" to "anon";

grant trigger on table "public"."receivables" to "anon";

grant truncate on table "public"."receivables" to "anon";

grant update on table "public"."receivables" to "anon";

grant delete on table "public"."receivables" to "authenticated";

grant insert on table "public"."receivables" to "authenticated";

grant references on table "public"."receivables" to "authenticated";

grant select on table "public"."receivables" to "authenticated";

grant trigger on table "public"."receivables" to "authenticated";

grant truncate on table "public"."receivables" to "authenticated";

grant update on table "public"."receivables" to "authenticated";

grant delete on table "public"."receivables" to "service_role";

grant insert on table "public"."receivables" to "service_role";

grant references on table "public"."receivables" to "service_role";

grant select on table "public"."receivables" to "service_role";

grant trigger on table "public"."receivables" to "service_role";

grant truncate on table "public"."receivables" to "service_role";

grant update on table "public"."receivables" to "service_role";

grant delete on table "public"."tms_agents" to "anon";

grant insert on table "public"."tms_agents" to "anon";

grant references on table "public"."tms_agents" to "anon";

grant select on table "public"."tms_agents" to "anon";

grant trigger on table "public"."tms_agents" to "anon";

grant truncate on table "public"."tms_agents" to "anon";

grant update on table "public"."tms_agents" to "anon";

grant delete on table "public"."tms_agents" to "authenticated";

grant insert on table "public"."tms_agents" to "authenticated";

grant references on table "public"."tms_agents" to "authenticated";

grant select on table "public"."tms_agents" to "authenticated";

grant trigger on table "public"."tms_agents" to "authenticated";

grant truncate on table "public"."tms_agents" to "authenticated";

grant update on table "public"."tms_agents" to "authenticated";

grant delete on table "public"."tms_agents" to "service_role";

grant insert on table "public"."tms_agents" to "service_role";

grant references on table "public"."tms_agents" to "service_role";

grant select on table "public"."tms_agents" to "service_role";

grant trigger on table "public"."tms_agents" to "service_role";

grant truncate on table "public"."tms_agents" to "service_role";

grant update on table "public"."tms_agents" to "service_role";

grant delete on table "public"."tms_carriers" to "anon";

grant insert on table "public"."tms_carriers" to "anon";

grant references on table "public"."tms_carriers" to "anon";

grant select on table "public"."tms_carriers" to "anon";

grant trigger on table "public"."tms_carriers" to "anon";

grant truncate on table "public"."tms_carriers" to "anon";

grant update on table "public"."tms_carriers" to "anon";

grant delete on table "public"."tms_carriers" to "authenticated";

grant insert on table "public"."tms_carriers" to "authenticated";

grant references on table "public"."tms_carriers" to "authenticated";

grant select on table "public"."tms_carriers" to "authenticated";

grant trigger on table "public"."tms_carriers" to "authenticated";

grant truncate on table "public"."tms_carriers" to "authenticated";

grant update on table "public"."tms_carriers" to "authenticated";

grant delete on table "public"."tms_carriers" to "service_role";

grant insert on table "public"."tms_carriers" to "service_role";

grant references on table "public"."tms_carriers" to "service_role";

grant select on table "public"."tms_carriers" to "service_role";

grant trigger on table "public"."tms_carriers" to "service_role";

grant truncate on table "public"."tms_carriers" to "service_role";

grant update on table "public"."tms_carriers" to "service_role";

grant delete on table "public"."tms_customers" to "anon";

grant insert on table "public"."tms_customers" to "anon";

grant references on table "public"."tms_customers" to "anon";

grant select on table "public"."tms_customers" to "anon";

grant trigger on table "public"."tms_customers" to "anon";

grant truncate on table "public"."tms_customers" to "anon";

grant update on table "public"."tms_customers" to "anon";

grant delete on table "public"."tms_customers" to "authenticated";

grant insert on table "public"."tms_customers" to "authenticated";

grant references on table "public"."tms_customers" to "authenticated";

grant select on table "public"."tms_customers" to "authenticated";

grant trigger on table "public"."tms_customers" to "authenticated";

grant truncate on table "public"."tms_customers" to "authenticated";

grant update on table "public"."tms_customers" to "authenticated";

grant delete on table "public"."tms_customers" to "service_role";

grant insert on table "public"."tms_customers" to "service_role";

grant references on table "public"."tms_customers" to "service_role";

grant select on table "public"."tms_customers" to "service_role";

grant trigger on table "public"."tms_customers" to "service_role";

grant truncate on table "public"."tms_customers" to "service_role";

grant update on table "public"."tms_customers" to "service_role";

grant delete on table "public"."tms_settings" to "anon";

grant insert on table "public"."tms_settings" to "anon";

grant references on table "public"."tms_settings" to "anon";

grant select on table "public"."tms_settings" to "anon";

grant trigger on table "public"."tms_settings" to "anon";

grant truncate on table "public"."tms_settings" to "anon";

grant update on table "public"."tms_settings" to "anon";

grant delete on table "public"."tms_settings" to "authenticated";

grant insert on table "public"."tms_settings" to "authenticated";

grant references on table "public"."tms_settings" to "authenticated";

grant select on table "public"."tms_settings" to "authenticated";

grant trigger on table "public"."tms_settings" to "authenticated";

grant truncate on table "public"."tms_settings" to "authenticated";

grant update on table "public"."tms_settings" to "authenticated";

grant delete on table "public"."tms_settings" to "service_role";

grant insert on table "public"."tms_settings" to "service_role";

grant references on table "public"."tms_settings" to "service_role";

grant select on table "public"."tms_settings" to "service_role";

grant trigger on table "public"."tms_settings" to "service_role";

grant truncate on table "public"."tms_settings" to "service_role";

grant update on table "public"."tms_settings" to "service_role";

grant delete on table "public"."tms_users" to "anon";

grant insert on table "public"."tms_users" to "anon";

grant references on table "public"."tms_users" to "anon";

grant select on table "public"."tms_users" to "anon";

grant trigger on table "public"."tms_users" to "anon";

grant truncate on table "public"."tms_users" to "anon";

grant update on table "public"."tms_users" to "anon";

grant delete on table "public"."tms_users" to "authenticated";

grant insert on table "public"."tms_users" to "authenticated";

grant references on table "public"."tms_users" to "authenticated";

grant select on table "public"."tms_users" to "authenticated";

grant trigger on table "public"."tms_users" to "authenticated";

grant truncate on table "public"."tms_users" to "authenticated";

grant update on table "public"."tms_users" to "authenticated";

grant delete on table "public"."tms_users" to "service_role";

grant insert on table "public"."tms_users" to "service_role";

grant references on table "public"."tms_users" to "service_role";

grant select on table "public"."tms_users" to "service_role";

grant trigger on table "public"."tms_users" to "service_role";

grant truncate on table "public"."tms_users" to "service_role";

grant update on table "public"."tms_users" to "service_role";


  create policy "Admin Full Access - Activity Logs"
  on "public"."activity_logs"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Commissions"
  on "public"."agent_commissions"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Agent Goals"
  on "public"."agent_goals"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Agent Performance"
  on "public"."agent_performance"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Read Access"
  on "public"."carrier_applications"
  as permissive
  for select
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Public Insert Carrier Apps"
  on "public"."carrier_applications"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "Admin Full Access - CRM Activities"
  on "public"."crm_activities"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - CRM Opportunities"
  on "public"."crm_opportunities"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Expenses"
  on "public"."expenses"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Invoices"
  on "public"."invoices"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Loads"
  on "public"."loads"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Payments"
  on "public"."payments"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Receivables"
  on "public"."receivables"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Agents"
  on "public"."tms_agents"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Carriers"
  on "public"."tms_carriers"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Customers"
  on "public"."tms_customers"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - Settings"
  on "public"."tms_settings"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));



  create policy "Admin Full Access - TMS Users"
  on "public"."tms_users"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'email'::text) = 'ozan@loyalbrokerage.com'::text));


CREATE TRIGGER on_carrier_signup AFTER INSERT ON public.carrier_applications FOR EACH ROW EXECUTE FUNCTION public.trigger_carrier_signup_email();

CREATE TRIGGER "new-quote-email" AFTER INSERT ON public.quotes FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://cfcrttsxeaugwfuoirod.supabase.co/functions/v1/request-quote-email', 'POST', '{}', '{}', '5000');


  create policy "Public Read Carrier Docs"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'carrier_docs'::text));



  create policy "Public Upload Carrier Docs"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'carrier_docs'::text));



  create policy "allow_read wndiqq_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'carrier_docs'::text));



  create policy "allow_upload wndiqq_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'carrier_docs'::text));



